### ISSUE TITLE
config_additional_variables format incorrect when nested config defined

### ISSUE THREAD

**Issue by jimmybigcommerce** [voxpupuli/puppet-rabbitmq#1040]
Not sure if this is a bug or a feature request, however if an array of values is passed into `rabbitmq::config_additional_variables`, the config that is generated is invalid.

Example:

Providing this config:
```
# hiera
rabbitmq::config_additional_variables:
  ra: 
    wal_max_size_bytes: 128000000
    segment_max_entries: 65535
```

The generated config stanza is:

```
  {ra, {"wal_max_size_bytes"=>128000000, "segment_max_entries"=>65535}}
```
however it should be:
```
{ra, [{segment_max_entries, 65535},{wal_max_size_bytes, 128000000}]}
```

**Comment by wyardley** [comment]
What if you mirror the structure of the config that should be generated (i.e., pass a map as the first element of an array) — does that work as expected?

**Comment by jimmybigcommerce** [comment]
Do you mean like this?

```
rabbitmq::config_additional_variables:
  ra:
    - segment_max_entries: 65535
    - wal_max_size_bytes: 134217728
```

Generated this:
```
{ra, [{"segment_max_entries"=>65535}, {"wal_max_size_bytes"=>134217728}]}
```

Which is slightly closer, but still has `=>` instead of commas.

The only thing that works is just putting the complete string the in the key (which is fine, but not perfect):

```
rabbitmq::config_additional_variables:
  ra: '[{segment_max_entries, 65535},{wal_max_size_bytes, 134217728}]'

```
